added option to run tar on host instead of a busybox container

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -376,6 +376,12 @@ command_export() {
     information 'Stopping containers' "$CONTAINERS"
     docker stop $CONTAINERS 1> /dev/null
   fi
+  restart_containers() {
+    if [ -n "$CONTAINERS" ]; then
+      information 'Restarting containers' "$CONTAINERS"
+      docker restart $CONTAINERS 1> /dev/null
+    fi
+  }
 
   TAR_OPTIONS='-zc'
   if [ $VERBOSE -eq 1 ]; then
@@ -384,23 +390,28 @@ command_export() {
   TAR_OPTIONS="${TAR_OPTIONS}f"
 
   information 'Exporting volume' "$VOLUME_NAME"
-  if ! docker run --rm \
-    -v "$VOLUME_NAME":/vackup-volume:ro \
-    -v "$DIRECTORY":/vackup \
-    busybox \
-    tar $TAR_OPTIONS /vackup/"$FILE_NAME" -C /vackup-volume .; then
-    if [ -n "$CONTAINERS" ]; then
-      information 'Restarting containers' "$CONTAINERS"
-      docker restart $CONTAINERS 1> /dev/null
+  if [ $HOST -eq 1 ]; then
+    MOUNTPOINT=$(docker inspect --format '{{ .Mountpoint }}' "$VOLUME_NAME") || {
+      restart_containers
+      error 'Failed to get the mountpoint'
+    }
+
+    if ! tar $TAR_OPTIONS "$DIRECTORY/$FILE_NAME" -C "$MOUNTPOINT" .; then
+      restart_containers
+      error 'Failed to tar the volume'
     fi
-
-    error 'Failed to start busybox backup container'
+  else
+    if ! docker run --rm \
+      -v "$VOLUME_NAME":/vackup-volume:ro \
+      -v "$DIRECTORY":/vackup \
+      busybox \
+      tar $TAR_OPTIONS /vackup/"$FILE_NAME" -C /vackup-volume .; then
+      restart_containers
+      error 'Failed to start busybox backup container'
+    fi
   fi
 
-  if [ -n "$CONTAINERS" ]; then
-    information 'Restarting containers' "$CONTAINERS"
-    docker restart $CONTAINERS 1> /dev/null
-  fi
+  restart_containers
 
   information --green 'Success' "Volume $VOLUME_NAME tar'ed into file '$FILE_NAME'"
 }
@@ -462,6 +473,12 @@ command_import() {
     information 'Stopping containers' "$CONTAINERS"
     docker stop $CONTAINERS 1> /dev/null
   fi
+  restart_containers() {
+    if [ -n "$CONTAINERS" ]; then
+      information 'Restarting containers' "$CONTAINERS"
+      docker restart $CONTAINERS 1> /dev/null
+    fi
+  }
 
   TAR_OPTIONS='-xz'
   if [ $VERBOSE -eq 1 ]; then
@@ -470,23 +487,28 @@ command_import() {
   TAR_OPTIONS="${TAR_OPTIONS}f"
 
   information 'Importing volume' "$VOLUME_NAME"
-  if ! docker run --rm \
-    -v "$VOLUME_NAME":/vackup-volume \
-    -v "$DIRECTORY/$FILE_NAME":"/vackup/$FILE_NAME":ro \
-    busybox \
-    tar $TAR_OPTIONS /vackup/"$FILE_NAME" -C /vackup-volume; then
-    if [ -n "$CONTAINERS" ]; then
-      information 'Restarting containers' "$CONTAINERS"
-      docker restart $CONTAINERS 1> /dev/null
+  if [ $HOST -eq 1 ]; then
+    MOUNTPOINT=$(docker inspect --format '{{ .Mountpoint }}' "$VOLUME_NAME") || {
+      restart_containers
+      error 'Failed to get the mountpoint'
+    }
+
+    if ! tar $TAR_OPTIONS "$DIRECTORY/$FILE_NAME" -C "$MOUNTPOINT"; then
+      restart_containers
+      error 'Failed to extract the tar archive into the volume'
     fi
-
-    error 'Failed to start busybox backup container'
+  else
+    if ! docker run --rm \
+      -v "$VOLUME_NAME":/vackup-volume \
+      -v "$DIRECTORY/$FILE_NAME":"/vackup/$FILE_NAME":ro \
+      busybox \
+      tar $TAR_OPTIONS /vackup/"$FILE_NAME" -C /vackup-volume; then
+      restart_containers
+      error 'Failed to start busybox backup container'
+    fi
   fi
 
-  if [ -n "$CONTAINERS" ]; then
-    information 'Restarting containers' "$CONTAINERS"
-    docker restart $CONTAINERS 1> /dev/null
-  fi
+  restart_containers
 
   information --green 'Success' "Archive '$FILE_NAME' unpacked into volume $VOLUME_NAME"
 }
@@ -690,6 +712,7 @@ command_all() {
 
 exec 3>&1
 VERBOSE=0
+HOST=0
 
 parse_command() {
   if [ $# -eq 0 ]; then
@@ -706,6 +729,8 @@ parse_command() {
     --quiet) exec 3>&1 1>/dev/null; parse_command "$@" ;;
     -v) VERBOSE=1 ; parse_command "$@" ;;
     --verbose) VERBOSE=1 ; parse_command "$@" ;;
+    -H) HOST=1 ; parse_command "$@" ;;
+    --host) HOST=1 ; parse_command "$@" ;;
     export) command_export "$@" ;;
     import) command_import "$@" ;;
     all) command_all "$@" ;;
