don't error out if chown fails
chown may fail when the destination file system doesn't support Unix ownership attributes. Since the success of chown isn't critical, if this happens, just print a warning and continue.

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -177,7 +177,7 @@ cmd_export() {
       -v "$VOLUME_NAME":/volume-data \
       -v "$DIRECTORY":/mount-volume \
       busybox \
-      /bin/sh -c 'tar -cvzf /mount-volume/'"'$FILE_NAME'"' -C /volume-data . && chown '"'${OWNER:-"$(id -u):$(id -g)"}'"' /mount-volume/'"'$FILE_NAME'";
+      /bin/sh -c 'tar -cvzf /mount-volume/'"'$FILE_NAME'"' -C /volume-data . && (chown '"'${OWNER:-"$(id -u):$(id -g)"}'"' /mount-volume/'"'$FILE_NAME'"' || echo 1>&2 "Warning: Failed to change ownership of the '"$FILE_NAME"' file")';
     then
         error 'Failed to start busybox backup container'
     fi
