implemented `all import` command

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -416,7 +416,83 @@ command_all_export() {
 }
 
 command_all_import() {
-  error 'Not implemented'
+  ARGS=''
+  STOP=0
+
+  while [ $# -ne 1 ]; do
+    case "$1" in
+      -*)
+        case "$1" in
+          -h) print_usage --exit ;;
+          --help) print_usage --exit ;;
+          -s) STOP=1 ;;
+          --stop) STOP=1 ;;
+          *) error usage "'$1' is not a recognized export option" ;;
+        esac
+
+        shift
+      ;;
+      *) break ;;
+    esac
+  done
+
+  case $# in
+    1) DIRECTORY="$1" ;;
+    *) error usage 'Wrong number of arguments' ;;
+  esac
+
+  case "$DIRECTORY" in
+    */) ;;
+    *)
+      if [ -f "$DIRECTORY" ]; then
+        error "'$DIRECTORY' is a file"
+      fi
+
+      DIRECTORY="$DIRECTORY/"
+    ;;
+  esac
+
+  if [ $STOP -eq 1 ]; then
+    CONTAINERS=$(docker ps -q)
+  else
+    CONTAINERS=''
+  fi
+
+  if [ -n "$CONTAINERS" ]; then
+    echo "Stopping containers: $CONTAINERS"
+    docker stop $CONTAINERS 1> /dev/null
+  fi
+
+  VOLUME_NAMES=$(docker volume ls -q)
+
+  SUCCESSFUL=''
+  FAILED=''
+  for VOLUME_NAME in $VOLUME_NAMES; do
+    FILE_NAME="$DIRECTORY$VOLUME_NAME.tar.gz"
+
+    if [ ! -f "$FILE_NAME" ]; then
+      warning "'$FILE_NAME' was not found, skipping import of '$VOLUME_NAME' volume"
+      continue
+    fi
+
+    if ! (command_import $ARGS "$FILE_NAME" "$VOLUME_NAME"); then
+      FAILED="$VOLUME_NAME"
+      break
+    fi
+
+    SUCCESSFUL="$SUCCESSFUL $VOLUME_NAME"
+  done
+
+  if [ -n "$CONTAINERS" ]; then
+    echo "Restarting containers: $CONTAINERS"
+    docker restart $CONTAINERS 1> /dev/null
+  fi
+
+  if [ -n "$FAILED" ]; then
+    error "Failed during $FAILED volume import"
+  fi
+
+  echo "Successfully unpacked archies into volumes [$SUCCESSFUL]"
 }
 
 command_all() {
