added option to print the license notice

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -240,6 +240,7 @@ Commands:
 
 Options:
   -h, --help        Print this help page and exit
+  -l, --license     Print the license notice and exit
   -q, --quiet       Silence the outputs to STDOUT, except if the help page is
                     explicitly requested
   -v, --verbose     Verbose printing
@@ -437,6 +438,66 @@ EOF
       TEXT=''
     ;;
   esac
+
+  if [ $STDERR -eq 1 ]; then
+    echo 1>&2 "$TEXT"
+  else
+    echo 1>&3 "$TEXT"
+  fi
+
+  if [ $EXIT -eq 1 ]; then
+    if [ $STDERR -eq 1 ]; then
+      if [ $CALLER -eq 1 ]; then
+        LINE_NUMBER=$(caller | awk '{ print $1 }') || LINE_NUMBER='unknown'
+        handle_error "$LINE_NUMBER" 1
+      else
+        exit 1
+      fi
+    else
+      exit 0
+    fi
+  fi
+}
+
+# Prints license notice and exits if necessary
+# Flags:
+#   --err: Print to STDERR instead of STDOUT
+#   --exit: Exit after printing usage.
+#           If --err is also set, exit with the error code 1
+print_license() {
+  STDERR=0
+  EXIT=0
+
+  while [ $# -ne 0 ]; do
+    case "$1" in
+      -*)
+        OPTION="$1"
+        shift
+
+        case "$OPTION" in
+          --err) STDERR=1 ;;
+          --exit) EXIT=1 ;;
+          *) warning "'$OPTION' is not a recognized print_license option"
+        esac
+      ;;
+      *) break ;;
+    esac
+  done
+
+  if [ $# -ne 0 ]; then
+    warning 'Wrong number of arguments in the print_license function'
+  fi
+
+  TEXT=$(cat <<EOF
+
+    $VACKUP Copyright (C) 2024  Guiorgy
+    This program comes with ABSOLUTELY NO WARRANTY.
+    This is free software, and you are welcome to redistribute it under certain
+    conditions.
+    Visit https://www.gnu.org/licenses/gpl-3.0.html for details.
+
+EOF
+  ) || error "Failed to generate the license notice text"
 
   if [ $STDERR -eq 1 ]; then
     echo 1>&2 "$TEXT"
@@ -1790,6 +1851,7 @@ HOST=0
 # Remark: Supports clustered flags, e.g. -abc instead of -a -b -c
 # Flags:
 #   -h, --help: Print the usage page and exit
+#   -l, --license: Print the license notice and exit
 #   -q, --quiet: Silence the outputs to STDOUT, except if the usage page is explicitly requested
 #   -v, --verbose: Verbose printing
 #   -H, --host: Do the export/import by running the archive program on the host instead of a container
@@ -1803,6 +1865,7 @@ while [ $# -gt 0 ]; do
   case "$COMMAND" in
     -[A-Za-z][A-Za-z]*) set -- $(prefix_all - $(chars 1 "$COMMAND")) "$@" ;;
     -h | --help | help) print_usage --exit ;;
+    -l | --license) print_license --exit ;;
     -q | --quiet) exec 3>&1 1>/dev/null ;;
     -v | --verbose) VERBOSE=1 ;;
     -H | --host) HOST=1 ;;
