reformatted export command docker run

diff --git a/vackup b/vackup
--- a/vackup
+++ b/vackup
@@ -1547,7 +1547,13 @@ command_export() {
       -v "$VOLUME_NAME":"$VOLUME_DATA_PATH":ro \
       -v "$DIRECTORY":"$ARCHIVE_FILE_PARENT_PATH" \
       busybox \
-      /bin/ash -c 'tar '"$TAR_OPTIONS"' '"'$FILE_CONTAINER_PATH'"' -C '"'$VOLUME_DATA_PATH'"' . && (chown '"'$OWNER'"' '"'$FILE_CONTAINER_PATH'"' || printf 1>&2 "%b" "${BOLD_YELLOW_COLOR_ERR}Warning${RESET_COLOR_ERR}: Failed to change ownership of the '"$FILE_NAME"' file\n")'; then
+        /bin/ash -c ' \
+          tar '"$TAR_OPTIONS"' '"'$FILE_CONTAINER_PATH'"' -C '"'$VOLUME_DATA_PATH'"' . \
+            && ( \
+              chown '"'$OWNER'"' '"'$FILE_CONTAINER_PATH'"' \
+                || printf 1>&2 "%b" "${BOLD_YELLOW_COLOR_ERR}Warning${RESET_COLOR_ERR}: Failed to change ownership of the '"$FILE_NAME"' file\n" \
+            ) \
+        '; then
       restart_containers $STOP_RESTART_CONTAINERS_ARGS
       error 'Failed to start busybox backup container'
     fi
